config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'
	 resources :popups, except: [:index, :show]
  resources :direct_orders, except: [:index, :show, :update, :destory]
  resources :inquiry_comments, except: [:index]
   resources :faqs, except: [:index]
   resources :orders, except: [:index, :show, :update, :destory]
   resources :review_comments, except: [:show]
   resources :question_comments, except: [:show]
   resources :questions, except: [:index, :show]
   resources :reviews, except: [:index, :show]
   resources :selects, except: [:index]
   resources :carts, except: [:index, :edit]
	 resources :mypage, only: [:destroy, :update], as: :inquiry
	 resources :payments, only: [:new, :create]

   resources :products, except: [:index]
   devise_for :users, :controllers => {:passwords => "passwords", :registrations => "registrations", :sessions => "sessions", :confirmaitions => "confirmations"}
   root 'home#category'
   resources :home, except: [:index, :create, :new, :destroy, :update]

	#get "/home" => 'home#category'
	get "/all" => 'home#index'
	get "/compare" => 'home#compare'

	post "/nonmember" => 'mypage#nonmember'
	get "/nonmember" => 'mypage#nonmember'
	get "/nonmember/refund/:id" => 'mypage#refund'
	post "/nonmember/refund/:id" => 'mypage#nonmember_refund'
	#고객행복센터	
	get "/happy" => 'home#happy' #FAQ
	get "/happy/FAQ" => 'home#happy' #FAQ
	get "/happy/shopping" => 'home#shopping' #이용안내
	get "/happy/refund" => 'home#refund' #반품/교환 안내
	#카테고리
	get "/category/:id" 	=> 'category#show'
  #결 제
	 get "/payments/complete" => 'payments#complete'
	 post "/payments/new"
   post "/orders/new" => 'orders#new'
	 get "/payments/refund/:id" => 'payments#refund'
	 get "/nonmember_direct_orders" =>'direct_orders#nonmember'
	 post "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_direct_orders" => 'direct_orders#nonmember'
	#환 불
	 post "/payments/refund" 
	#리 뷰
	 get "/reviews/new/:product_id" => 'reviews#new'
	 get "/review_comments/new/:review_id" => 'review_comments#new'
	#상품 질문
	 get "/questions/new/:product_id" => 'questions#new'
	 get "/question_comments/new/:question_id" => 'question_comments#new'
	#일대일 문의
	 get "/inquiry_comments/new/:inquiry_id" => 'inquiry_comments#new'
	 #장바구니
	 get "/cart/empty" => 'mypage#empty'
   #상품 페이지
   get "/products/:p_category/:id" => 'products#show' 
   #마이페이지
	 get "/mypage/purchase_statement"
   get "/mypage/exchange_return"  
   get "/mypage/my_activity"
   get "/mypage/user_information"
	 post "/mypage/user_information/edit" => 'mypage#user_information_edit'
   get "/mypage/FAQ"
	 get "/mypage" => 'mypage#purchase_statement'
	 post "mypage/FAQ" => 'mypage#create'
	 get "/mypage/:id" => 'mypage#edit'
	 delete "/mypage/FAQ/:id" => 'mypage#destroy'
	 get "/mypage/purchase_statement/:id" => 'mypage#order_info' #주문정보
	 get "/mypage/exchange_question/:id" => 'mypage#exchange_question' #교환문의
	 post "/mypage/exchange_question/:id/" => 'mypage#exchange_create'
	 get "/mypage/cancel/:id" => 'mypage#cancel_request'
	 get "/mypage/point/details" => 'mypage#point'
	 post "/mypage/refund_vbank" 

   #관리자 페이지
	 post "/admin/paymentstatus"
   get "/admin" => 'admin#index'
	 get "/admin/product_upload" => 'products#new'
	 get "/admin/product_management"
	 get "/admin/product_management/:id" => 'admin#soldout'
	 get "/admin/customer_db"
	 get "/admin/order_delivery"
	 get "/admin/order_deposit"
	 get "/admin/operation_review"
	 get "/admin/operation_alram"
	 get "/admin/operation_question"
	 get "/admin/operation_faq"
	 get "/admin/operation_inquiry"
	 get "/admin/exchange_question"
	 post "/admin/exchange_question" => 'admin#exchange_complete'
	 get "/admin/refund_question"
	 post "/admin/refund_question" => 'admin#refund_complete'
	 get "/admin/payments"
	 get "/admin/order_delivery/:id" => 'admin#transnum'
	 get "/admin/point" => 'admin#point'
	 post "/admin/point" => 'admin#point_create'
	 get "/admin/point_info" => 'admin#point_info'
	 get "/admin/customer_db/:id" => 'admin#customer_info'
   get "/admin/manual" => 'admin#manual'
	 get "/admin/popup" => 'admin#popup'
	 get "/admin/popup/true" => 'admin#popup_true'
	 get "/admin/popup/false" => 'admin#popup_false'
	 get "/admin/sale"
	 # 서비스 페이지(회사소개, 이용안내 ..)
	 get 'service/agreement'
	 get 'service/about'
	 get 'service/private'
	 get 'service/guide'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_upmenu.html.erb
 <body>
		   <div class="grid" style="margin: 5px; border: 1px solid #bdbdbd;">
               <table class="table">
                 <tr>
                  <th style="width: 30%;">
                      결제(총 건수/미결제/결제완료/취소및환불)
                  </th>
                  <th style="width: 70%;">
                      (<%= @payments.count %>/<%= @payments.where(status:'ready').count %>/<%= @payments.where(status:'paid').count %>/<%= @payments.where(status:'cancelled').count %>)
                  </th>
                 </tr>
                <tr>
                  <th style="width: 30%;">
                      배송(총 건수/배송준비/배송중/배송완료)
                  </th>
                  <th style="width: 70%;">
									    (<%= @trans.count %>/<%= @trans.where(status:'배송출발').count +  @trans.where(status:'집화출발').count +  @trans.where(status:'집화처리' ).count %>/<%= @trans.count -  @trans.where(status:'배송출발').count -  @trans.where(status:'집화출발').count- @trans.where(status:'집화처리' ).count -  @trans.where(status:'배달완료').count %>/<%= @trans.where(status:'배달완료').count %>)
                </th>
                 </tr>
                 <tr>
                  <th style="width: 30%;">
									    교환(총 건수/교환신청/교환완료)
                  </th>
                  <th style="width: 70%;">
									 (<%= @refunds.count %>/<%= @refunds.where(status:'start').count %>/<%= @refunds.where(status:'complete').count %>)
                  </th>
                 </tr>
								 <tr>
                  <th style="width: 30%;">
                      반품(총 건수/반품신청/반품완료)
                  </th>
                  <th style="width: 70%;">
									  (<%= @exchanges.count %>/<%= @exchanges.where(status:'start').count %>/<%= @exchanges.where(status:'complete').count %>)
                  </th>
                 </tr>
               </table>
    </div>
    </br></br>
  </body>

app/views/admin/customer_db.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
    <%= render "sidemenu" %>
    
            <h5>고객 DB</h5>
	<span>다운로드: <%= link_to "CSV", admin_customer_db_path(format: "csv") %> | <%= link_to "Excel", admin_customer_db_path(format: "xls") %></span>
	
	<%= form_tag(admin_customer_db_path, method: :get) do %>
  <%= text_field_tag :name, params[:name], placeholder:"이름 또는 이메일  또는 전화번호로 검색 가능" %>
  <%= submit_tag '검색', name: nil %>
<% end %>
<div class="big_box">
	 <div class="small_box">
                <table>
                  <thead>
                    <tr>
											<th>순번</th>
                      <th>가입일</th>
											<th>이름</th>
                      <th>이메일</th>
                      <th>전화번호</th>
                      <th>성별</th>
                      <th>회원등급</th>
                      <th>최근구매일</th>
                      <th colspan="5"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @user.each do |user| %>
                      <tr>
                        <td><%= user.id %></td>
                        <td><%= user.created_at.strftime("%Y.%m.%d") %></td>
                  		  <td><a href="/admin/customer_db/<%= user.id %>"> <%= user.name %></a></td>
                        <td><a href="/admin/customer_db/<%= user.id %>"><%= user.email %></a></td>
                        <td><%= user.phone_number %></td>
                        <td><%= user.sex %></td>
                        <td>회원등급</td>
                       <% if user.payments.last %><td><%= user.payments.last.created_at.strftime("%Y.%m.%d") %></td><% else %><td>없음</td><% end %>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
						</div>
        </div>
</div>
  </body>
</html>

app/views/admin/index.html.erb
<div class="login_box">
    <div class="newyork">
        <h4><strong>속도가 아니라 방향이다</strong></h4>
        <h5>미국으로 가는 문을 열자</h5></br>
        <a class="adminimg" href="/admin/product_upload"><%= image_tag 'newyork.jpg' %></a>
    </div>
</div>

app/views/admin/operation_inquiry.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
    <%= render "sidemenu" %>
    
              <h5>일대일문의</h5>
              <div class="big_box">
                <div class="small_box">
    <ul class="collapsible" data-collapsible="accordion">
               <% @inquiry.each do |inquiry| %>
               <% user = inquiry.user %>
							 <% inquiry_comment = inquiry.inquiry_comment%>
                            <li>
                                <div class="collapsible-header" style="font-size: 14px;">
                                 &emsp;<%= inquiry.id %>&emsp;&emsp;&emsp;<%= inquiry.created_at.strftime("%Y.%m.%d") %>&emsp;&emsp;&emsp;<% if inquiry_comment %>답변완료<% else %>답변중<% end %>&emsp;&emsp;&emsp;&nbsp;<%= inquiry.title %>&emsp;
                                </div>
                                <div class="collapsible-body" style="font-size: 14px;">
                                    <span>
                                     <div>
                                            <%= inquiry.content %>
                                        </div>
                                               			 <div>

																										<% if ! inquiry_comment %> <div style="text-align: right;"><a href="/inquiry_comments/new/<%= inquiry.id %>">답글</a> </div> 
																										<% else %>
                                                    </br>
                                                    &emsp;<span style="border: 1px solid black; border-radius: 2px; padding: 0px 15px 0px 15px;">답변</span></br>
																										&emsp;<%= inquiry_comment.title %></br></br>
																									  &emsp;&emsp;<%= inquiry_comment.content %>
                                                         <div style="text-align: right;">
                                                             </br>
                                                   <%= link_to '수정', edit_inquiry_comment_path(inquiry_comment), class:"borderbox" %>&emsp;<%= link_to '삭제', inquiry_comment, method: :delete, data: { confirm: '답글을 삭제하시겠습니까?'  }    , class: "borderbox" %>
                                                         </div>
                                                 <% end %>
                                                </div>
                                        </span>
                                    </div>
                                </li>
               <% end %>
     </ul>
					
		
							</div>
              </div>
            </div>

  </div>
</body>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="js/materialize.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

	<script>
            $(document).ready(function () {
                $('.slider').slider({
		    full_width: true,
		    indicators: false
		});
            });
	</script>

	<script>
	    $(document).ready(function(){
         	 $('.slider').slider('pause');
            });
	</script>

	<script>
	    $(document).ready(function(){
          $('.next').click(function() {
             $('.slider').slider('next');
          });
          $('.prev').click(function() {
             $('.slider').slider('prev');
          });
        });
	</script>

       <script>
	(function($)
        $(document).ready(function(){
            $('.collapsible').collapsible();
        });
	}) (jQuery);
       </script>
</html>

app/views/admin/operation_question.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
    <%= render "sidemenu" %>
    
              <h5>문의</h5>
              <div class="big_box">
                <div class="small_box">
                  <table>
                    <thead>
                      <tr>
                        <th>문의 번호</th>
                        <th>상품 번호</th>
                        <th>상품명</th>
                        <th>제목</th>
                        <th>고객 성명</th>
												<th>답변 상태</th>
                        <th colspan="5"></th>
                      </tr>
                    </thead>
 
                    <tbody>
                     <% @question.each do |question| %>
                        <% product = question.product %>
                        <% user = question.user %>
												<% question_comment = question.question_comment %>
                        <tr>
                          <td><%= question.id %></td>
                          <td><%= question.product_id %></td>
                          <td><%= product.p_title %></td>
                          <td><%= question.q_title %></td>
                          <td><%= user.name %></td>
													<% if question_comment %>
													<td>답변완료</td>
													<% else %>
													<td>답변중</td>
													<% end %>
                          <td><a href=/products/<%= product.id %>#tab-react>보기</a></td> <!-- show 페이지 없어서 그에 해당하는 상품 페이지로 -->
                          <td><%= link_to '수정', edit_question_path(question) %></td>
                          <td><%= link_to '삭제', question, method: :delete, data: { confirm: '삭제하시겠습니까?' } %></td>
													<% if ! question_comment %>
													<td><a href="/question_comments/new/<%= question.id %>">답글</a></td>
													<% end %>
                        </tr>
												<% if question_comment %>
												<% admin = question_comment.user %>
												<tr>
													<td><%= question.id %></td>
													<td><%= question.product_id %></td>
													<td><%= product.p_title %></td>
													<td><%= question_comment.qc_title %></td>
													<td><%= admin.name %></td>
													<td></td>
												  <td><a href=/products/<%= product.id %>#tab-react>보기</a></td> <!-- show 페이지 없어서 그에 해당하는 상품 페이지로 -->
												  <td><%= link_to '수정', edit_question_comment_path(question_comment) %></td>
												  <td><%= link_to '삭제', question_comment, method: :delete, data: { confirm: '삭제하시겠습니까?' } %></td>
												</tr>
											  <% end %>
                    <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
 
      </div>

app/views/admin/order_delivery.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  
	<Worksheet ss:Name="Sheet1">
    
		<Table>
      <Row>
		<Cell><Data ss:Type="String">받는분성명</Data></Cell>
    <Cell><Data ss:Type="String">받는분전화번호</Data></Cell>
		<Cell><Data ss:Type="String">받는분기타연락처</Data></Cell>
    <Cell><Data ss:Type="String">받는분우편번호</Data></Cell>
    <Cell><Data ss:Type="String">받는분주소(전체, 분할)</Data></Cell>
    <Cell><Data ss:Type="String">품목명</Data></Cell>
		<Cell><Data ss:Type="String">내품수량</Data></Cell>
    <Cell><Data ss:Type="String">배송메세지1</Data></Cell>
		<Cell><Data ss:Type="String">구매일</Data></Cell>

      </Row>

    <% @payments.each do |payment| %>
		<% user = payment.user %>
		<% selects = payment.selects %>
		<% num = 0 %>
    <% selects.each do |select| %>
    <% num += select.product_quantity %>
    <% end %>
			<Row>
		<Cell><Data ss:Type="String"><%= user.name  %></Data></Cell>
    <Cell><Data ss:Type="String"><%= user.phone_number %></Data></Cell>
		 <Cell><Data ss:Type="String"><%= user.phone_number %></Data></Cell>
    <Cell><Data ss:Type="String"><%= user.postcode3 %></Data></Cell>
    <Cell><Data ss:Type="String"><%= user.address5 %>//<%= user.address6 %></Data></Cell>
    <Cell><Data ss:Type="String"><%= payment.name %></Data></Cell>
		<Cell><Data ss:Type="Number"><%= num %></Data></Cell>
    <Cell><Data ss:Type="String"><%= payment.request %></Data></Cell>
		<Cell><Data ss:Type="String"><%= payment.created_at.strftime("%Y년 %m월 %d일 %H시")%></Data></Cell>
      </Row>
    <% end %>
    </Table>

  </Worksheet>
</Workbook>

app/views/admin/payments.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
    <%= render(:partial => "sidemenu" ,:controller=>"sidemenu") %>

		 					 
              <h5>결제</h5>
		 <%= form_tag(admin_payments_path, method: :get) do %>
 			 <%= text_field_tag :merchant_uid, params[:merchant_uid], placeholder: "주문번호 또는 상태로 검색가능" %>
  			<%= submit_tag '검색', name: nil %>
		 <% end %>
              <div class="big_box">
                <div class="small_box">
    <ul class="collapsible" data-collapsible="accordion">
               <% @payments.each do |payment| %>
               <% user = payment.user %>
                            <li>
                                <div class="collapsible-header" style="font-size: 14px;">
                                 &emsp;<%= payment.id %>&emsp;&emsp;&emsp;<%= payment.created_at.strftime("%Y.%m.%d") %>&emsp;&emsp;&emsp;<%= payment.merchant_uid%>&emsp;&emsp;&emsp;&nbsp;<%= payment.name %>&emsp;
																 <% if payment.status == "paid" %>결제완료<% elsif payment.status == "ready" %>미결제<% elsif payment.status == "cancelled" %>결제취소<% end %>&emsp;&emsp;&emsp;&nbsp;
																 <% if payment.cancelrq == "request" %>취소요청<% elsif payment.cancelrq == "complete" %>취소완료<% end %>
                                </div>
                                <div class="collapsible-body" style="font-size: 14px;">
                                    <span>
                                     <div>
                                     <div class="small_box">
																		 <h6 style="font-size: 22px; font-weight: 500; margin-bottom: 20px;">&nbsp;&nbsp;배송정보</h6>
           <div class="grid" style="margin: 0px 5px 0px 5px;">
            <table class="table">
            <tr>
             <th style="width: 30%;">수령인</th>
             <td style="width: 70%;"><%= payment.buyer_name %></td>
           </tr>
           <tr>
             <th style="width: 30%;">연락처</th>
             <td style="width: 70%;"><%= payment.buyer_tel %></td>
           </tr>
              <tr>
             <th style="width: 30%;">배송주소</th>
             <td style="width: 70%;">
              (<%= payment.buyer_postcode %>)<%= payment.buyer_addr %>
           </tr>
           <tr>
             <th style="width: 30%;">요청사항</th>
             <td style="width: 70%;"><%= payment.request %></td>
           </tr>
           </table>
           </div>
            </br>


<h6 style="font-size: 22px; font-weight: 500; margin-bottom: 20px;">&nbsp;&nbsp;결제정보</h6>
           <div class="grid" style="margin: 0px 5px 10px 5px;">
            <table class="table">
            <tr>
             <th style="width: 30%;">결제수단</th>

             <td style="width: 70%;"><% if payment.pay_method == 'card' %>신용카드<% elsif payment.pay_method == 'trans'%>실시간계좌이체<% elsif payment.pay_method == 'vbank'%>가상계좌<%  elsif payment.pay_method == 'phone'%>휴대폰소
액결제 <% end %>
</td>
           </tr>
           <tr>
             <th style="width: 30%;">결제금액</th>
             <td style="width: 70%;"><%= number_to_currency(payment.amount, precision: 0, unit: "원", format: "%n %u") %></td>
           </tr>
              <tr>
             <th style="width: 30%;">영수증</th>
             <td style="width: 70%;">
      <a title="" href="#:" onClick="window.open('<%= payment.receipt_url %>','1','status=yes,scrollbars=yes,width=500,height=850')" style="cursor:pointer; font-size: 14px;">
                    <button style="background: white; color: #42a5f5; border: 1px solid #42a5f5; border-radius: 2px; padding: 1px 20px 1px 20px; margin-bottom: 5px; ">영수증보기</button>
                </a>
           </tr>
          </table>
          </div>
          </br>
		<h6 style="font-size: 22px; font-weight: 500; margin-bottom: 20px;">&nbsp;&nbsp;주문 상품</h6>
				<div class="grid" style="margin: 0px 5px 10px 5px;">
					<% payment.selects.each do |select| %>		
						 <table class="table">
            <tr>
             <th style="width: 30%;">상품명</th>
				<td style="width: 70%;"><%= select.product.p_title %></td>
			</tr>
			<tr>
			 <th style="width: 30%;">주문수량</th>
				<td style="width: 70%;">	<%= select.product_quantity %></td>
			</tr>
			<tr>
			 <th style="width: 30%;">주문사이즈</th>
				<td style="width: 70%;"><%= select.selected_size %></td>
			</tr>
			<tr>
			 <th style="width: 30%;">주문색상</th>
			 <td style="width: 70%;"><%= select.selected_colorname %></td>
			</tr>
						</table>
					<% end %>					
				 </div></br>

<% if payment.pay_method == "vbank" && payment.refund_num && payment.refund_bank %>
   <h6 style="font-size: 22px; font-weight: 500; margin-bottom: 20px;">&nbsp;&nbsp;환불 계좌</h6>
        <div class="grid" style="margin: 0px 5px 10px 5px;">
             <table class="table">
            <tr>
             <th style="width: 30%;">계좌 번호</th>
        <td style="width: 70%;"><%= payment.refund_num %></td>
      </tr>
      <tr>
       <th style="width: 30%;">은행명</th>
        <td style="width: 70%;"><%= payment.refund_bank %></td>
      </tr>
      <tr>
       <th style="width: 30%;">예금주</th>
        <td style="width: 70%;"><% if payment.refund_name %><%= payment.refund_name %><% else %><%= payment.user.name %><% end %></td>
      </tr>
            </table>
         </div></br>
<% end %>


						<% if payment.pay_method == "vbank" %>
						 가상계좌는 직접 환불해야 됩니다.
						<% else %>
					 <% if payment.status == "paid" %><a href="/payments/refund/<%= payment.imp_uid %>">환불</a><% else %><button disabled>환불완료</button><% end %>
					 <% end %>
                                          </div>
                                        </div>
                                        </span>
                                    </div>
                                </li>
				<% end %>
     </ul>

              </div>
              </div>
            </div>
</div>
</body>
<script type="text/javascript" src="js/materialize.min.js"></script>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

  <script>
            $(document).ready(function () {
                $('.slider').slider({
        full_width: true,
        indicators: false
    });
            });
  </script>

  <script>
      $(document).ready(function(){
           $('.slider').slider('pause');
            });
  </script>

  <script>
      $(document).ready(function(){
          $('.next').click(function() {
             $('.slider').slider('next');
          });
          $('.prev').click(function() {
             $('.slider').slider('prev');
          });
        });
  </script>

       <script>
  (function($)
        $(document).ready(function(){
            $('.collapsible').collapsible();
        });
  }) (jQuery);
       </script>
</html>

app/views/admin/point.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
    <%= render "sidemenu" %>
    
            <h5>포인트관리</h5>
						 <div class="big_box">
                <div class="small_box">
<form action="/admin/point" method="post">

    </br>
    <div class="field">
		내용
		<input type="text" name="name"  placeholder="ex)반품/취소에 의한 포인트 반환/회수">
    </div>

    <div class="field">
		적립금
		 <input type="text" name="amount"  placeholder="ex)600">
		</div>

		<div class="field">
		사용/적립(add/use)
		 <input type="text" name="method"  placeholder="ex)use or add">
		 </div>

		 <div class="field">
		  주문번호
      <input type="text" name="payment_merchant_uid" placeholder="ex)merchant_1231231231231">
      </div>

			고객 이메일
  	  <div class="field">
			 <input type="text" name="user_email" placeholder="ex)je941004@naver.com">
		 </div>

		<div class="actions">
	   	<input type="submit" value="확인">
  	</div>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		</form>
								</div>
						</div>
	</div>
</div>

app/views/admin/point_info.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
    <%= render "sidemenu" %>

<h4><strong>&nbsp;포인트 사용내역</strong></h4></br>
 <%= form_tag(admin_point_info_path, method: :get) do %>
  <%= text_field_tag :name, params[:name], placeholder: "이메일로 검색 가능" %>
  <%= submit_tag '검색', name: nil %>
<% end %>

        <div class="cart" style="border: 1px solid #bdbdbd; margin-bottom: 30px; padding: 0px;">

          <table>
                    <thead style="border-bottom: 1px solid #bdbdbd;">
                      <tr>
                        <th class="point">날짜</th>
												<th class="point">아이디</th>
                        <th class="point">내용</th>
                        <th class="point">내역</th>
                      </tr>
                    </thead>

                    <tbody>

                    <% @point.each do |point| %>
										<% user = point.user %>
                    <% if point.payment_id %>
                    <% payment = point.payment  %>

                    <tr>
                      <td class="point"><%= point.created_at.strftime("%Y.%m.%d") %></td>
											<td class="point"><%= user.email %></td> 
                      <% if payment.merchant_uid %>
                      <td class="point"><%= point.name %></br> <a href="/mypage/purchase_statement/<%= payment.id%>"><%= payment.merchant_uid.last(13) %></a><% else %><span></span><% end%></td>
                        <% if point.method == 'add' %>
                        <span><td class="point">+<%= number_to_currency(point.amount.to_i, precision: 0, unit: "원", format: "%n %u")  %></td></span>
                        <% else %>
                      <td class="point"><span style="color: red;">-<%= number_to_currency(point.amount.to_i, precision: 0, unit: "원", format: "%n %u")  %></span></td>
                        <% end %>
                    </tr>

                    <% else %>

                      <tr>
                          <td class="point"><%= point.created_at.strftime("%Y.%m.%d") %></td>
													<td class="point"><%= user.email %></td>
                          <td class="point"><%= point.name %></td>
                          <% if point.method == 'add' %>
                          <span><td class="point">+<%= number_to_currency(point.amount.to_i, precision: 0, unit: "원", format: "%n %u")  %></td></span>
                          <% else %>
                          <td class="point"><span style="color: red;">-<%= number_to_currency(point.amount.to_i, precision: 0, unit: "원", format: "%n %u")  %></span></td>
                          <% end %>
                        </tr>
                      <% end %>
                    <% end %>

                    </tbody>
                  </table>
        </div>
		</div>
	</div>
</body>
</html>

app/views/admin/popup.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="container">
    <%= render "sidemenu" %>
    
            <h5>팝업</h5>
						 <div class="big_box">
                <div class="small_box">
					<% unless @popup %>
						<a href="/popups/new">팝업 만들기</a>
						<% else %>
							 <table>
                  <thead>
                    <tr>                      
                      <th>넓이</th>
                      <th>높이</th>
					  <th>이미지</th>
                      <th colspan="5"></th>
                    </tr>
                  </thead>
                  <tbody>
                      <tr>
                        <td><%= @popup.width %></td>
                        <td><%= @popup.height %></td>
                        <td><img src="<%= @popup.image.url %>" style="width: 80px; height:auto;"></td>
                        <td><%= link_to '수정', edit_popup_path(@popup) %></td>
						<% unless @popup.status %><td><a href="/admin/popup/true">팝업창 띄우기 실행</a></td>
							<% else %><td><a href="/admin/popup/false">팝업창 띄우기 종료</a></td><% end %>
                      </tr>
                  </tbody>
                </table>
						<% end %>
								</div>
						</div>
	</div>
</div>