config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'
	 resources :popups, except: [:index, :show]
  resources :direct_orders, except: [:index, :show, :update, :destory]
  resources :inquiry_comments, except: [:index]
   resources :faqs, except: [:index]
   resources :orders, except: [:index, :show, :update, :destory]
   resources :review_comments, except: [:show]
   resources :question_comments, except: [:show]
   resources :questions, except: [:index, :show]
   resources :reviews, except: [:index, :show]
   resources :selects, except: [:index]
   resources :carts, except: [:index, :edit]
	 resources :mypage, only: [:destroy, :update], as: :inquiry
	 resources :payments, only: [:new, :create]

   resources :products, except: [:index]
   devise_for :users, :controllers => {:passwords => "passwords", :registrations => "registrations", :sessions => "sessions", :confirmaitions => "confirmations"}
   root 'home#category'
   resources :home, except: [:index, :create, :new, :destroy, :update]

	#get "/home" => 'home#category'
	get "/all" => 'home#index'
	get "/compare" => 'home#compare'

	post "/nonmember" => 'mypage#nonmember'
	get "/nonmember" => 'mypage#nonmember'
	get "/nonmember/refund/:id" => 'mypage#refund'
	post "/nonmember/refund/:id" => 'mypage#nonmember_refund'
	#고객행복센터	
	get "/happy" => 'home#happy' #FAQ
	get "/happy/FAQ" => 'home#happy' #FAQ
	get "/happy/shopping" => 'home#shopping' #이용안내
	get "/happy/refund" => 'home#refund' #반품/교환 안내
	#카테고리
	get "/category/:id" 	=> 'category#show'
  #결 제
	 get "/payments/complete" => 'payments#complete'
	 post "/payments/new"
   post "/orders/new" => 'orders#new'
	 get "/payments/refund/:id" => 'payments#refund'
	 get "/nonmember_direct_orders" =>'direct_orders#nonmember'
	 post "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_direct_orders" => 'direct_orders#nonmember'
	#환 불
	 post "/payments/refund" 
	#리 뷰
	 get "/reviews/new/:product_id" => 'reviews#new'
	 get "/review_comments/new/:review_id" => 'review_comments#new'
	#상품 질문
	 get "/questions/new/:product_id" => 'questions#new'
	 get "/question_comments/new/:question_id" => 'question_comments#new'
	#일대일 문의
	 get "/inquiry_comments/new/:inquiry_id" => 'inquiry_comments#new'
	 #장바구니
	 get "/cart/empty" => 'mypage#empty'
   #상품 페이지
   get "/products/:p_category/:id" => 'products#show' 
   #마이페이지
	 get "/mypage/purchase_statement"
   get "/mypage/exchange_return"  
   get "/mypage/my_activity"
   get "/mypage/user_information"
	 post "/mypage/user_information/edit" => 'mypage#user_information_edit'
   get "/mypage/FAQ"
	 get "/mypage" => 'mypage#purchase_statement'
	 post "mypage/FAQ" => 'mypage#create'
	 get "/mypage/:id" => 'mypage#edit'
	 delete "/mypage/FAQ/:id" => 'mypage#destroy'
	 get "/mypage/purchase_statement/:id" => 'mypage#order_info' #주문정보
	 get "/mypage/exchange_question/:id" => 'mypage#exchange_question' #교환문의
	 post "/mypage/exchange_question/:id/" => 'mypage#exchange_create'
	 get "/mypage/cancel/:id" => 'mypage#cancel_request'
	 get "/mypage/point/details" => 'mypage#point'
	 post "/mypage/refund_vbank" 

   #관리자 페이지
	 post "/admin/paymentstatus"
   get "/admin" => 'admin#index'
	 get "/admin/product_upload" => 'products#new'
	 get "/admin/product_management"
	 get "/admin/product_management/:id" => 'admin#soldout'
	 get "/admin/customer_db"
	 get "/admin/order_delivery"
	 get "/admin/order_deposit"
	 get "/admin/operation_review"
	 get "/admin/operation_alram"
	 get "/admin/operation_question"
	 get "/admin/operation_faq"
	 get "/admin/operation_inquiry"
	 get "/admin/exchange_question"
	 post "/admin/exchange_question" => 'admin#exchange_complete'
	 get "/admin/refund_question"
	 post "/admin/refund_question" => 'admin#refund_complete'
	 get "/admin/payments"
	 get "/admin/order_delivery/:id" => 'admin#transnum'
	 get "/admin/point" => 'admin#point'
	 post "/admin/point" => 'admin#point_create'
	 get "/admin/point_info" => 'admin#point_info'
	 get "/admin/customer_db/:id" => 'admin#customer_info'
   get "/admin/manual" => 'admin#manual'
	 get "/admin/popup" => 'admin#popup'
	 get "/admin/popup/true" => 'admin#popup_true'
	 get "/admin/popup/false" => 'admin#popup_false'
	 get "/admin/sale"
	 # 서비스 페이지(회사소개, 이용안내 ..)
	 get 'service/agreement'
	 get 'service/about'
	 get 'service/private'
	 get 'service/guide'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/question_comments_controller.rb
class QuestionCommentsController < ApplicationController
  before_action :set_question_comment, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin1
	before_action :authenticate_admin

  # GET /question_comments
  # GET /question_comments.json
  def index
    @question_comments = QuestionComment.all
  end

  # GET /question_comments/1
  # GET /question_comments/1.json
  def show
  end

  # GET /question_comments/new
  def new
    @question_comment = QuestionComment.new
		@question = Question.find(params[:question_id])
		session[:question_id] = params[:question_id]
		@user = current_user
  end

  # GET /question_comments/1/edit
  def edit
  end

  # POST /question_comments
  # POST /question_comments.json
  def create
    @question_comment = QuestionComment.new(question_comment_params)
	  @user = current_user
	  @question_comment.question_id = session[:question_id]
	  @question_comment.user_id = @user.id
	  @question = Question.find(session[:question_id])

    respond_to do |format|
      if @question_comment.save
        format.html { redirect_to admin_operation_question_path, notice: 'Question comment was successfully created.' }
        format.json { render :show, status: :created, location: @question_comment }
				session[:question_id] = nil
      else
        format.html { render :new }
        format.json { render json: @question_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_comments/1
  # PATCH/PUT /question_comments/1.json
  def update
	@question = @question_comment.question
  @product = @question.product
    respond_to do |format|
      if @question_comment.update(question_comment_params)
        format.html { redirect_to @product, notice: 'Question comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_comment }
      else
        format.html { render :edit }
        format.json { render json: @question_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_comments/1
  # DELETE /question_comments/1.json
  def destroy
    @question_comment.destroy
    respond_to do |format|
      format.html { redirect_to question_comments_url, notice: 'Question comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_comment
      @question_comment = QuestionComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_comment_params
      params.require(:question_comment).permit(:user_id, :question_id, :qc_title, :qc_comment)
    end
end

app/helpers/question_comments_helper.rb
module QuestionCommentsHelper
end

app/views/question_comments/_form.html.erb
<%= form_for(question_comment) do |f| %>
  <% if question_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_comment.errors.count, "error") %> prohibited this question_comment from being saved:</h2>

      <ul>
      <% question_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :question_id %>
    <%= f.text_field :question_id %>
  </div>

  <div class="field">
    <%= f.label :qc_title %>
    <%= f.text_field :qc_title %>
  </div>

  <div class="field">
    <%= f.label :qc_comment %>
    <%= f.text_area :qc_comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_comments/edit.html.erb
<h1>Editing Question Comment</h1>

<%= render 'form', question_comment: @question_comment %>

<%= link_to 'Show', @question_comment %> |
<%= link_to 'Back', question_comments_path %>

app/views/question_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Qc title</th>
      <th>Qc comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_comments.each do |question_comment| %>
      <tr>
        <td><%= question_comment.user %></td>
        <td><%= question_comment.question %></td>
        <td><%= question_comment.qc_title %></td>
        <td><%= question_comment.qc_comment %></td>
        <td><%= link_to 'Show', question_comment %></td>
        <td><%= link_to 'Edit', edit_question_comment_path(question_comment) %></td>
        <td><%= link_to 'Destroy', question_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Comment', new_question_comment_path %>

app/views/question_comments/new.html.erb
<h1>New Question Comment</h1>

<%= render 'form', question_comment: @question_comment %>

<%= link_to 'Back', question_comments_path %>

app/views/question_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @question_comment.user %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question_comment.question %>
</p>

<p>
  <strong>Qc title:</strong>
  <%= @question_comment.qc_title %>
</p>

<p>
  <strong>Qc comment:</strong>
  <%= @question_comment.qc_comment %>
</p>

<%= link_to 'Edit', edit_question_comment_path(@question_comment) %> |
<%= link_to 'Back', question_comments_path %>