config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'
	 resources :popups, except: [:index, :show]
  resources :direct_orders, except: [:index, :show, :update, :destory]
  resources :inquiry_comments, except: [:index]
   resources :faqs, except: [:index]
   resources :orders, except: [:index, :show, :update, :destory]
   resources :review_comments, except: [:show]
   resources :question_comments, except: [:show]
   resources :questions, except: [:index, :show]
   resources :reviews, except: [:index, :show]
   resources :selects, except: [:index]
   resources :carts, except: [:index, :edit]
	 resources :mypage, only: [:destroy, :update], as: :inquiry
	 resources :payments, only: [:new, :create]

   resources :products, except: [:index]
   devise_for :users, :controllers => {:passwords => "passwords", :registrations => "registrations", :sessions => "sessions", :confirmaitions => "confirmations"}
   root 'home#category'
   resources :home, except: [:index, :create, :new, :destroy, :update]

	#get "/home" => 'home#category'
	get "/all" => 'home#index'
	get "/compare" => 'home#compare'

	post "/nonmember" => 'mypage#nonmember'
	get "/nonmember" => 'mypage#nonmember'
	get "/nonmember/refund/:id" => 'mypage#refund'
	post "/nonmember/refund/:id" => 'mypage#nonmember_refund'
	#고객행복센터	
	get "/happy" => 'home#happy' #FAQ
	get "/happy/FAQ" => 'home#happy' #FAQ
	get "/happy/shopping" => 'home#shopping' #이용안내
	get "/happy/refund" => 'home#refund' #반품/교환 안내
	#카테고리
	get "/category/:id" 	=> 'category#show'
  #결 제
	 get "/payments/complete" => 'payments#complete'
	 post "/payments/new"
   post "/orders/new" => 'orders#new'
	 get "/payments/refund/:id" => 'payments#refund'
	 get "/nonmember_direct_orders" =>'direct_orders#nonmember'
	 post "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_direct_orders" => 'direct_orders#nonmember'
	#환 불
	 post "/payments/refund" 
	#리 뷰
	 get "/reviews/new/:product_id" => 'reviews#new'
	 get "/review_comments/new/:review_id" => 'review_comments#new'
	#상품 질문
	 get "/questions/new/:product_id" => 'questions#new'
	 get "/question_comments/new/:question_id" => 'question_comments#new'
	#일대일 문의
	 get "/inquiry_comments/new/:inquiry_id" => 'inquiry_comments#new'
	 #장바구니
	 get "/cart/empty" => 'mypage#empty'
   #상품 페이지
   get "/products/:p_category/:id" => 'products#show' 
   #마이페이지
	 get "/mypage/purchase_statement"
   get "/mypage/exchange_return"  
   get "/mypage/my_activity"
   get "/mypage/user_information"
	 post "/mypage/user_information/edit" => 'mypage#user_information_edit'
   get "/mypage/FAQ"
	 get "/mypage" => 'mypage#purchase_statement'
	 post "mypage/FAQ" => 'mypage#create'
	 get "/mypage/:id" => 'mypage#edit'
	 delete "/mypage/FAQ/:id" => 'mypage#destroy'
	 get "/mypage/purchase_statement/:id" => 'mypage#order_info' #주문정보
	 get "/mypage/exchange_question/:id" => 'mypage#exchange_question' #교환문의
	 post "/mypage/exchange_question/:id/" => 'mypage#exchange_create'
	 get "/mypage/cancel/:id" => 'mypage#cancel_request'
	 get "/mypage/point/details" => 'mypage#point'
	 post "/mypage/refund_vbank" 

   #관리자 페이지
	 post "/admin/paymentstatus"
   get "/admin" => 'admin#index'
	 get "/admin/product_upload" => 'products#new'
	 get "/admin/product_management"
	 get "/admin/product_management/:id" => 'admin#soldout'
	 get "/admin/customer_db"
	 get "/admin/order_delivery"
	 get "/admin/order_deposit"
	 get "/admin/operation_review"
	 get "/admin/operation_alram"
	 get "/admin/operation_question"
	 get "/admin/operation_faq"
	 get "/admin/operation_inquiry"
	 get "/admin/exchange_question"
	 post "/admin/exchange_question" => 'admin#exchange_complete'
	 get "/admin/refund_question"
	 post "/admin/refund_question" => 'admin#refund_complete'
	 get "/admin/payments"
	 get "/admin/order_delivery/:id" => 'admin#transnum'
	 get "/admin/point" => 'admin#point'
	 post "/admin/point" => 'admin#point_create'
	 get "/admin/point_info" => 'admin#point_info'
	 get "/admin/customer_db/:id" => 'admin#customer_info'
   get "/admin/manual" => 'admin#manual'
	 get "/admin/popup" => 'admin#popup'
	 get "/admin/popup/true" => 'admin#popup_true'
	 get "/admin/popup/false" => 'admin#popup_false'
	 get "/admin/sale"
	 # 서비스 페이지(회사소개, 이용안내 ..)
	 get 'service/agreement'
	 get 'service/about'
	 get 'service/private'
	 get 'service/guide'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :selects
	belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
	if user_signed_in?
	 if current_user.bucket != @cart.id
		 redirect_to '/'
	 end
	end
	   select = @cart.selects.order('created_at desc')
	   @select = select.where.not(status: 'soldout')

	end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
     @cart.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(cart) do |f| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="cart-box">
  <div class="cart-boxbox">
    <h4><strong>&nbsp;장바구니</strong></h4>
    <div class="cart" style="border: 1px solid #bdbdbd; margin-bottom: 30px; padding: 0px;">
    </br>
    <% if @select.count > 0 %>
        <% count = @select.count %>
        <% @select.each do |item| %>
        <div class="row" style="height: auto; margin: 2px 10px 18px 10px; border: 1px solid #bdbdbd; padding: 0px 8px 0px 8px;">
            <div class="col l1 s1" style="text-align: center; padding: 30px 0px 30px 0px;">
              </br></br></br></br>
              <span style="border: 1px solid #bdbdbd; padding: 2px 5px 2px 5px;">
                <%= count %>
              </span>
            </div>
            <% count -= 1 %>
            <div class="col l8 s7" style="vertical-align: middle; padding: 30px 0px 30px 0px;">
              <div class="row">
                <div class="col l4 s12" style="text-align: center;">
                   </br>
                   <a href="/products/<%= item.product.p_category %>/<%= item.product.id %>">
              <img src="<%= item.product.m_image.url %>" style="width: 130px; height: 160px;" />
              </a>
            </div>

            <div class="col l8 s12" style="padding-left: 30px;">
                 </br>
                   <a href="/products/<%= item.product.p_category %>/<%= item.product.id %>" style="color: black; font-weight: 600;">

               <%= item.product.p_title %>
               </a></br>
							 <span style="font-weight: 700; margin-bottom: 15px;">색&nbsp;&nbsp;상 : </span><%= item.selected_colorname %></br>
               <span style="font-weight: 700; margin-bottom: 15px;">치&nbsp;&nbsp;수 : </span><%= item.selected_size.upcase %></br>
               <span style="font-weight: 700; margin-bottom: 15px;">금&nbsp;&nbsp;액 : </span>
               <% item.s_price = item.product.p_price.to_i * item.product_quantity %>
               <%= number_to_currency(item.s_price, precision: 0, unit: "원", format: "%n %u") %>
               </br>
               <span style="font-weight: 700; margin-bottom: 15px;">설&nbsp;&nbsp;명 : </span>
               <a href="/products/<%= item.product.p_category %>/<%= item.product.id %>" style="color: black;">
               <%= item.product.p_comment %>
               </a>
            </div>
          </div>
          </div>

          <div class="col l3 s4" style="padding: 30px 0px 30px 0px; text-align: center; vertical-align: middle;">
              </br>
            <%= form_for (item) do |f| %>
              <%  f.hidden_field :s_price %>
                    <%= f.text_field :product_quantity, style: 'width: 40px; text-align: center;' %></br>
                    <%= button_to '수정', item, method: :get, style: "text-decoration: none; border: 1px solid #42a5f5; background: white; color: #42a5f5; border-radius: 1.5px; padding: 4px 30px 4px 30px; font-size: 13px;" %></br>
                    <%= button_to '삭제', item, method: :delete, style: "text-decoration: none; border: 1px solid #42a5f5; background: white; color: #42a5f5; border-radius: 1.5px; padding: 4px 30px 4px 30px; font-size: 13px;", data: { confirm: '해당 상품을 삭제 하시겠습니까?' } %>
                  <% end %>
            </div>
          </div>

        <% end %>
    <% else %>
        <div class="row" style="border: 1px solid #bdbdbd; margin: 0px 10px 10px 10px;">
              <p style="text-align: center; padding: 35px; font-weight: 400;">담겨진 상품이 없습니다.</p>
            </div>
    <% end %>
        <div style="display: flex;">
        <%= button_to '카트 비우기', cart_path, method: :delete, class: "borderboxbox", style: "text-decoration: none; margin-left: 10px;", data: { confirm: '카트를 비우시겠습니까?' } %>
        <%= link_to '쇼핑하기', root_path, class: "borderboxbox", style: "text-decoration: none; margin-left: 7px; padding-top: 3px;" %>
        </div>
      <div class="cart" style="border: 0px;">
        <% first = 0 %>
        <% @select.each do |item| %>
        <% product_price = item.product.p_price.to_i * item.product_quantity %>
        <% cart_total_price = product_price + first %>
        <% first = cart_total_price %>
          <% end %>

        <div class="pricebox">
         <div class="row" style="padding-top: 10px;">
          <div class="col l4 s12">
            <p>
            총 <%= @select.count %>개의 상품금액
            <%= number_to_currency(first, precision: 0, unit: "원", format: "%n %u") %>
            </p>
           </div>
           <div class="col l3 s12">
            <p>
            <%= image_tag 'add.png' %>&emsp;
            배송비<% if first < 30000 && first > 0  %> 2,500<% else %> 0<%end%> 원
            </p>
           </div>
           <div class="col l5 s12">
            <p>
            <%= image_tag 'equa.png' %>&emsp;
            <% if first < 30000 && first > 0 %><% first = first + 2500 %><% end %>
            총 주문금액
            <span style="font-weight: 600;"><%= number_to_currency(first, precision: 0, unit: "원", format: "%n %u") %></span>
            </p>
          </div>
         </div>
        </div>
        </br>
        </br>
				<% if user_signed_in? %>
        <%= button_to '주문하기', orders_new_path, method: :post , class: 'submit-button' %>
				<% else %>
				<%= button_to '비회원 주문하기',  nonmember_orders_path, method: :post , class: 'submit-button' %>
				<% end %>
      </div>
    </div>
  </div>
</div>