config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'
	 resources :popups, except: [:index, :show]
  resources :direct_orders, except: [:index, :show, :update, :destory]
  resources :inquiry_comments, except: [:index]
   resources :faqs, except: [:index]
   resources :orders, except: [:index, :show, :update, :destory]
   resources :review_comments, except: [:show]
   resources :question_comments, except: [:show]
   resources :questions, except: [:index, :show]
   resources :reviews, except: [:index, :show]
   resources :selects, except: [:index]
   resources :carts, except: [:index, :edit]
	 resources :mypage, only: [:destroy, :update], as: :inquiry
	 resources :payments, only: [:new, :create]

   resources :products, except: [:index]
   devise_for :users, :controllers => {:passwords => "passwords", :registrations => "registrations", :sessions => "sessions", :confirmaitions => "confirmations"}
   root 'home#category'
   resources :home, except: [:index, :create, :new, :destroy, :update]

	#get "/home" => 'home#category'
	get "/all" => 'home#index'
	get "/compare" => 'home#compare'

	post "/nonmember" => 'mypage#nonmember'
	get "/nonmember" => 'mypage#nonmember'
	get "/nonmember/refund/:id" => 'mypage#refund'
	post "/nonmember/refund/:id" => 'mypage#nonmember_refund'
	#고객행복센터	
	get "/happy" => 'home#happy' #FAQ
	get "/happy/FAQ" => 'home#happy' #FAQ
	get "/happy/shopping" => 'home#shopping' #이용안내
	get "/happy/refund" => 'home#refund' #반품/교환 안내
	#카테고리
	get "/category/:id" 	=> 'category#show'
  #결 제
	 get "/payments/complete" => 'payments#complete'
	 post "/payments/new"
   post "/orders/new" => 'orders#new'
	 get "/payments/refund/:id" => 'payments#refund'
	 get "/nonmember_direct_orders" =>'direct_orders#nonmember'
	 post "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_orders" => 'orders#nonmember'
	 get "/nonmember_direct_orders" => 'direct_orders#nonmember'
	#환 불
	 post "/payments/refund" 
	#리 뷰
	 get "/reviews/new/:product_id" => 'reviews#new'
	 get "/review_comments/new/:review_id" => 'review_comments#new'
	#상품 질문
	 get "/questions/new/:product_id" => 'questions#new'
	 get "/question_comments/new/:question_id" => 'question_comments#new'
	#일대일 문의
	 get "/inquiry_comments/new/:inquiry_id" => 'inquiry_comments#new'
	 #장바구니
	 get "/cart/empty" => 'mypage#empty'
   #상품 페이지
   get "/products/:p_category/:id" => 'products#show' 
   #마이페이지
	 get "/mypage/purchase_statement"
   get "/mypage/exchange_return"  
   get "/mypage/my_activity"
   get "/mypage/user_information"
	 post "/mypage/user_information/edit" => 'mypage#user_information_edit'
   get "/mypage/FAQ"
	 get "/mypage" => 'mypage#purchase_statement'
	 post "mypage/FAQ" => 'mypage#create'
	 get "/mypage/:id" => 'mypage#edit'
	 delete "/mypage/FAQ/:id" => 'mypage#destroy'
	 get "/mypage/purchase_statement/:id" => 'mypage#order_info' #주문정보
	 get "/mypage/exchange_question/:id" => 'mypage#exchange_question' #교환문의
	 post "/mypage/exchange_question/:id/" => 'mypage#exchange_create'
	 get "/mypage/cancel/:id" => 'mypage#cancel_request'
	 get "/mypage/point/details" => 'mypage#point'
	 post "/mypage/refund_vbank" 

   #관리자 페이지
	 post "/admin/paymentstatus"
   get "/admin" => 'admin#index'
	 get "/admin/product_upload" => 'products#new'
	 get "/admin/product_management"
	 get "/admin/product_management/:id" => 'admin#soldout'
	 get "/admin/customer_db"
	 get "/admin/order_delivery"
	 get "/admin/order_deposit"
	 get "/admin/operation_review"
	 get "/admin/operation_alram"
	 get "/admin/operation_question"
	 get "/admin/operation_faq"
	 get "/admin/operation_inquiry"
	 get "/admin/exchange_question"
	 post "/admin/exchange_question" => 'admin#exchange_complete'
	 get "/admin/refund_question"
	 post "/admin/refund_question" => 'admin#refund_complete'
	 get "/admin/payments"
	 get "/admin/order_delivery/:id" => 'admin#transnum'
	 get "/admin/point" => 'admin#point'
	 post "/admin/point" => 'admin#point_create'
	 get "/admin/point_info" => 'admin#point_info'
	 get "/admin/customer_db/:id" => 'admin#customer_info'
   get "/admin/manual" => 'admin#manual'
	 get "/admin/popup" => 'admin#popup'
	 get "/admin/popup/true" => 'admin#popup_true'
	 get "/admin/popup/false" => 'admin#popup_false'
	 get "/admin/sale"
	 # 서비스 페이지(회사소개, 이용안내 ..)
	 get 'service/agreement'
	 get 'service/about'
	 get 'service/private'
	 get 'service/guide'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/popup.rb
class Popup < ApplicationRecord
mount_uploader :image, PopupImageUploader
end

app/controllers/popups_controller.rb
class PopupsController < ApplicationController
  before_action :set_popup, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin1
  before_action :authenticate_admin


  # GET /popups
  # GET /popups.json
  def index
    @popups = Popup.all
  end

  # GET /popups/1
  # GET /popups/1.json
  def show
  end

  # GET /popups/new
  def new
    @popup = Popup.new
  end

  # GET /popups/1/edit
  def edit
  end

  # POST /popups
  # POST /popups.json
  def create
    @popup = Popup.new(popup_params)

    respond_to do |format|
      if @popup.save
        format.html { redirect_to '/admin/popup', notice: 'Popup was successfully created.' }
        format.json { render :show, status: :created, location: @popup }
      else
        format.html { render :new }
        format.json { render json: @popup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /popups/1
  # PATCH/PUT /popups/1.json
  def update
    respond_to do |format|
      if @popup.update(popup_params)
        format.html { redirect_to '/admin/popup', notice: 'Popup was successfully updated.' }
        format.json { render :show, status: :ok, location: @popup }
      else
        format.html { render :edit }
        format.json { render json: @popup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /popups/1
  # DELETE /popups/1.json
  def destroy
    @popup.destroy
    respond_to do |format|
      format.html { redirect_to popups_url, notice: 'Popup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_popup
      @popup = Popup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def popup_params
      params.require(:popup).permit(:image, :status, :width, :height)
    end
end

app/helpers/popups_helper.rb
module PopupsHelper
end

app/views/popups/_form.html.erb
<%= form_for(popup) do |f| %>
  <% if popup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(popup.errors.count, "error") %> prohibited this popup from being saved:</h2>

      <ul>
      <% popup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	  
  <div class="field">
        <%= f.label :image, "팝업 이미지" %></br>
        <%= f.file_field :image %></br>
  </div>

  <div class="field">
    <%= f.label :width %>
    <%= f.text_field :width %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>

   <div class="actions">
        <%= f.submit "팝업등록", class:"submit-button", data: {confirm: '팝업을 등록하시겠습니까?'} %>
      </div>
   <% end %>

app/views/popups/edit.html.erb
<h1>Editing Popup</h1>

<%= render 'form', popup: @popup %>

<%= link_to 'Show', @popup %> |
<%= link_to 'Back', popups_path %>

app/views/popups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Popups</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Status</th>
      <th>Width</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @popups.each do |popup| %>
      <tr>
        <td><%= popup.image %></td>
        <td><%= popup.status %></td>
        <td><%= popup.width %></td>
        <td><%= popup.height %></td>
        <td><%= link_to 'Show', popup %></td>
        <td><%= link_to 'Edit', edit_popup_path(popup) %></td>
        <td><%= link_to 'Destroy', popup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Popup', new_popup_path %>

app/views/popups/new.html.erb
<h1>New Popup</h1>

<%= render 'form', popup: @popup %>

<%= link_to 'Back', popups_path %>

app/views/popups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @popup.image %>
</p>

<p>
  <strong>Status:</strong>
  <%= @popup.status %>
</p>

<p>
  <strong>Width:</strong>
  <%= @popup.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @popup.height %>
</p>

<%= link_to 'Edit', edit_popup_path(@popup) %> |
<%= link_to 'Back', popups_path %>